package com.yzp.jfinaltest.model;

import com.yzp.jfinaltest.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	
}
