package com.yzp.jfinaltest.model;

import com.yzp.jfinaltest.model.base.BaseUjfinal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ujfinal extends BaseUjfinal<Ujfinal> {
	
}
